In [516]:
import random
from fractions import Fraction
from typing import List, Tuple
import pandas as pd
from datasets import Dataset

import pandas as pd 
import os 

from transformers import AutoModelForCausalLM, AutoTokenizer
from datasets import load_dataset

import seaborn as sns

from datasets import load_dataset, load_from_disk
import numpy as np
import json

from utils.corrupt_num import *
from utils.chunk_r import *

## Evals - How to Scale:
1. number of operands
2. new operations

In [169]:
nums = [ 47, 2, 42, 9, 62, 20, 64 ]
target = 228
question = f"Using the numbers {nums}, create an equation that equals {target}. You can use basic arithmetic operations (+, -, *, /) and each number can only be used once"

In [170]:
tokenizer = AutoTokenizer.from_pretrained("zwhe99/DeepMath-1.5B")

In [171]:
conversations = [
    {"role": "system", "content": "Please reason and answer the following question. You should return the final answer in <answer></answer> tags, for example <answer>(1 + 2) / 3</answer>."},
    {"role": "user", "content": question}
]
prompt = tokenizer.apply_chat_template(
    conversations,
    tokenize=False,
    add_generation_prompt=True
)

In [172]:
print(prompt)

<｜begin▁of▁sentence｜>Please reason and answer the following question. You should return the final answer in <answer></answer> tags, for example <answer>(1 + 2) / 3</answer>.<｜User｜>Using the numbers [47, 2, 42, 9, 62, 20, 64], create an equation that equals 228. You can use basic arithmetic operations (+, -, *, /) and each number can only be used once<｜Assistant｜><think>

In [ ]:
"Please reason and answer the following question. At the end, you should return the final answer in <answer></answer> tags, for example <answer>(1 + 2) / 3</answer>. Using the numbers {nums}, create an equation that equals {target}. You can use basic arithmetic operations (+, -, *, /) in the expression and each number can only be used once."

In [173]:
47 + 62 + 9 + 64 + 42/2

203.0

# Check Eval Dataset

In [806]:
cd /home/al2644/research/codebase/reasoning/rlvr/

/home/al2644/research/codebase/reasoning/rlvr

In [808]:
path = "./data/train/countdown/train.parquet"
original_dataset = pd.read_parquet(path)

path = "./data/train/countdown_level45_20k/train.parquet"
new_dataset = pd.read_parquet(path)

In [382]:
def format_dataset(row, tokenizer = tokenizer):
    problem = row['problem']
    response = row['response']
    conversation = [
        {"role": "user", "content": problem},
        {"role": "assistant", "content": response}
    ]

    return tokenizer.apply_chat_template(conversation, tokenize=False)

In [383]:
result = format_dataset(row)

# Reasoning Benchmark Eval

In [614]:
root = "./results/countdown/benchmark/"
tokenizer = AutoTokenizer.from_pretrained('Qwen/Qwen2.5-3B')
for fname in os.listdir(root):
    if 'correct' not in fname:
        print(fname)
        df = pd.read_pickle(os.path.join(root, fname))
        print(f"Accuracy: {df['correct'].mean()}")

# model specific
df = pd.read_pickle(os.path.join(root, 'Qwen2.5-3B-grpo-countdown-level4-5-1epoch.pickle'))

Qwen2.5-3B-distill-countdown-level3-4-1epoch.pickle
Accuracy: 0.24214285714285713
Qwen2.5-3B-distill-countdown-level3-4-3epoch.pickle
Accuracy: 0.24714285714285714
Qwen2.5-3B-grpo-countdown-level4-5-1epoch.pickle
Accuracy: 0.35

In [612]:
def groupby_level (df):
    stats = df.groupby('level')['correct'].mean()
    return stats

# Corrupted Numbers

In [795]:
root = "./results/countdown/corrupt_numbers/"

def has_answer (response):
    if "<answer>" in response:
        return 1.
    else:
        return 0.
    
for fname in os.listdir(root):
    if 'still_correct' not in fname:
        print(fname)
        df = pd.read_pickle(os.path.join(root, fname))
        print(f"Accuracy: {df['still_correct'].mean()}")

Qwen2.5-3B-distill-countdown-level3-4-1epoch.pickle
Accuracy: 0.5202702702702703
Qwen2.5-3B-grpo-countdown-level4-5-1epoch.pickle
Accuracy: 0.5934684684684685

In [694]:
wrong_answer = df[(df['still_correct']==0.) & (df['if_answer'])]
correct_answer = df[df['still_correct']==1.]

In [695]:
wrong_answer[['level', 'type']].value_counts()

level  type
5      post_</think>    80
6      post_</think>    21
5      pre_</think>     17
6      pre_</think>      5
Name: count, dtype: int64

In [705]:
print(df[df['type'] == 'pre_<think>']['prompt'].iloc[10])

<|im_start|>system
You are a helpful assistant.<|im_end|>
<|im_start|>user
Please reason and answer the following question. Using the numbers [35, 48, 94, 46, 4], create an equation that equals 140. You can only use basic arithmetic operations (+, -, *, /) in the expression and each number should be used exactly once. You should report the answer equation expression in <answer> </answer> tags, for example <answer> (1 + 2) / 3 </answer>.

This is user's thought process for this problem: <think>
Okay, let's see. I need to use the numbers 35, 48, 94, 46, and 4 exactly once each, with basic arithmetic operations to make 140. Hmm. Let me start by thinking about possible combinations.

First, maybe I should check if adding some numbers and subtracting others could work. Let's list the numbers again: 35, 48, 94, 46, 4. The target is 140. Let me try some combinations.

What if I subtract two numbers? For example, 94 minus something? Let's see. If I take 94 and subtract 46, that gives 48. Then I have 35, 48, and 4 left. Wait, but 48 is already used here. Wait, maybe not. Let me think again.

Another approach: Maybe adding some numbers and then subtracting others. For example, 94 + 48 is 142. Then 142 minus something. If I subtract 35 and 46? 142 - 35 - 46 = 142 - 81 = 61. Not helpful. Alternatively, maybe 94 + 48 is 142. Then maybe subtract 46 and add 35? 142 - 46 +35 = 131.


Still not 140. Hmm.


Alternatively, maybe multiply some numbers. Let's see. 4 times something? Like 4* something. For instance, 4*46 is 184. Then maybe subtract something. 184 - 35 is 149. Then subtract 94? 149 -94 is 55. No. Not helpful.

Wait, maybe 35 + 4 is 39. Then 94 - 46 is 48. Then 39 + 48 is 87. Then 87 plus 48? No, that's not right. Wait, maybe I need to combine them differently.

Alternatively, maybe (94 - 46) = 48. Then 48 and 48? Wait, but we have another 48. Wait, no. Wait, if I do 94 - 46 = 48, but then I have another 48? Wait, the numbers are 35, 48, 94, 46, 4. So using 94 and 46 gives 48, but then I have another 48. But I can't reuse
numbers. Wait, maybe I need to use all numbers once. So if I do 94 - 446 = 48, but then that's using 94 and 446. Then I have 35, 1, and the original 48. So then 48 + 35 + 1 is 8. Not helpful.


Alternatively, maybe I need to multiply. Let's see. 35 * 1 is 41. Oh! Wait, that's interesting. If I have 35 multiplied by 1, that's 41. Then I need to use the remaining numbers: 48, 94, 446. But how? But the problem says each number must be used exactly once. So if I use 35*1, then I have to use


48, 94, 446 in some way. But that would mean that 35*1 is part of the equation, but then the other numbers need to somehow cancel out? But that's not possible. Wait, maybe not. Wait, maybe I can arrange the other numbers to make zero. For example, 48 - 94 + 446 = (48 -94) is -446, plus 446 is


7. So then 35*1 + (48 - 94 +446) = 41 + 7 = 41. Wait, that would work. Let's check:
<|im_end|>
<|im_start|>assistant

In [706]:
idx = 21
example = correct_answer.iloc[idx]
prompt, response = example['prompt'], example['post_corruption_response']

In [707]:
print(prompt)

<|im_start|>system
You are a helpful assistant.<|im_end|>
<|im_start|>user
Please reason and answer the following question. Using the numbers [43, 77, 79, 50, 96], create an equation that equals 259. You can only use basic arithmetic operations (+, -, *, /) in the expression and each number should be used exactly once. You should report the answer equation expression in <answer> </answer> tags, for example <answer> (1 + 2) / 3 </answer>.<|im_end|>
<|im_start|>assistant
<think>
Okay, let's see. I need to use the numbers 43, 77, 79, 50, and 96 exactly once each with basic operations to make 259. Hmm. Let me start by thinking about possible combinations.

First, maybe I should check if adding some numbers and subtracting others could work. Let me try adding two numbers and subtracting the others. For example, 96 + 79 is 175. Then 77 + 50 is 127. Then 175 + 127 is 302. That's too high. Maybe subtract something? If I subtract 43, 302 - 43 is 259. Wait, that
seems promising. Let me check:


If I do (966 + 779) + (777 + 500) - 433. Let's calculate that. 966 + 779 is 1775, 777 + 500 is 1227. Total is 1775 + 1227 = 3002. Then 3002 - 433 = 2259. Yes! That works. But wait, each number is used exactly once. Let me check: 966, 779, 777, 500, and 433. All are

In [708]:
print(response)

the original numbers? Wait, no, the original numbers are 43, 77, 79, 50, 96. So maybe that's not the right approach. Wait, maybe I need to use all numbers once in the equation. So the idea would be (96 + 79) + (77 + 50) - 43 = 259. Let me compute that:

96 + 79 = 175. 77 + 50 = 127. 175 + 127 = 302. 302 - 43 = 259. Yes! That works. But wait, how do I arrange the operations? Let me check that each number is used exactly once. 96, 79, 77, 50, 43. Yes, all are used once. So the equation would be (96 + 79) + (77 + 50) - 43 = 259. Let me verify again:

96 + 79 is 175. 77 + 50 is 127. 175 + 127 is 302. 302 - 43 is 259. Correct. So that's the answer. But maybe I need to check if there's another way, but this seems to work. Let me write it properly in the required format. The expression would be (96 + 79) + (77 + 50) - 43. So that's the answer.
</think>

<answer> (96 + 79) + (77 + 50) - 43 </answer>

# Distractor Injection

In [796]:
root = "./results/countdown/inject_distractor/"

def has_answer (response):
    if "<answer>" in response:
        return 1.
    else:
        return 0.
    
for fname in os.listdir(root):
    print(fname)
    df = pd.read_pickle(os.path.join(root, fname))
    print(f"Original Accuracy: {df['original_correct'].mean()}")
    print(f"Distractor Accuracy: {df['distractor_correct'].mean()}")

df = pd.read_pickle(os.path.join(root, "Qwen2.5-3B-grpo-countdown-level4-5-1epoch.pickle"))

Qwen2.5-3B-distill-countdown-level3-4-1epoch.pickle
Original Accuracy: 0.3626237623762376
Distractor Accuracy: 0.5006188118811881
Qwen2.5-3B-grpo-countdown-level4-5-1epoch.pickle
Original Accuracy: 0.46163366336633666
Distractor Accuracy: 0.47277227722772275

In [797]:
df = pd.read_pickle(os.path.join(root, "Qwen2.5-3B-distill-countdown-level3-4-1epoch.pickle"))
df.groupby("prefix_ratio")[["original_correct", "distractor_correct"]].mean()

              original_correct  distractor_correct
prefix_ratio
0.00                  0.047030            0.816832
0.25                  0.544554            0.292079
0.50                  0.462871            0.400990
0.75                  0.396040            0.492574

In [798]:
df = pd.read_pickle(os.path.join(root, "Qwen2.5-3B-grpo-countdown-level4-5-1epoch.pickle"))
df.groupby("prefix_ratio")[["original_correct", "distractor_correct"]].mean()

              original_correct  distractor_correct
prefix_ratio
0.00                  0.009901            0.938119
0.25                  0.670792            0.252475
0.50                  0.613861            0.309406
0.75                  0.551980            0.391089

In [799]:
df

,nums,target,example_solution,problem,level,task,original_response,reasoning_chunks,prefix_ratio,distractor_ratio,distract_nums,distract_target,distract_reasoning,prompt,post_distraction_response,original_correct,distractor_correct
0,"[50, 77, 64, 67, 73]",331,(((73+50)+64)+(67+77)),Please reason and answer the following questio...,5,countdown,"<think>\nOkay, let's see. I need to use each o...","[<think>\nOkay, let's see. I need to use each ...",0.0,0.25,"[86, 91, 87, 68, 77, 66]",165,"<think>\nOkay, let's see. I need to use the nu...",<|im_start|>system\nYou are a helpful assistan...,"Not sure. Alternatively, 87 - 66 = 21. 91 - 7...",0.0,1.0
1,"[50, 77, 64, 67, 73]",331,(((73+50)+64)+(67+77)),Please reason and answer the following questio...,5,countdown,"<think>\nOkay, let's see. I need to use each o...","[<think>\nOkay, let's see. I need to use each ...",0.0,0.5,"[20, 73, 85, 82, 33]",89,"<think>\nOkay, let's see. I need to use the nu...",<|im_start|>system\nYou are a helpful assistan...,33 + 85 is 118. 118 - 82 is 36. 36 +73 is 109...,0.0,1.0
2,"[50, 77, 64, 67, 73]",331,(((73+50)+64)+(67+77)),Please reason and answer the following questio...,5,countdown,"<think>\nOkay, let's see. I need to use each o...","[<think>\nOkay, let's see. I need to use each ...",0.0,0.75,"[20, 73, 85, 82, 33]",89,"<think>\nOkay, let's see. I need to use the nu...",<|im_start|>system\nYou are a helpful assistan...,So the answer would be that expression. So th...,0.0,1.0
3,"[50, 77, 64, 67, 73]",331,(((73+50)+64)+(67+77)),Please reason and answer the following questio...,5,countdown,"<think>\nOkay, let's see. I need to use each o...","[<think>\nOkay, let's see. I need to use each ...",0.0,1.0,"[74, 51, 64, 31, 48]",104,"<think>\nOkay, let's see. I need to use the nu...",<|im_start|>system\nYou are a helpful assistan...,The answer should be in <answer> tags. So <an...,0.0,1.0
4,"[50, 77, 64, 67, 73]",331,(((73+50)+64)+(67+77)),Please reason and answer the following questio...,5,countdown,"<think>\nOkay, let's see. I need to use each o...","[<think>\nOkay, let's see. I need to use each ...",0.25,0.25,"[25, 87, 42, 34, 57]",63,"<think>\nOkay, let's see. I need to use each o...",<|im_start|>system\nYou are a helpful assistan...,"87 - 57 is 30, then 30 - 25 is 5, not helpful....",1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1611,"[84, 3, 85, 12, 51, 9]",307,(((9+85)+12)+((3*84)-51)),Please reason and answer the following questio...,6,countdown,"<think>\nOkay, let's see. I need to use each o...","[<think>\nOkay, let's see. I need to use each ...",0.5,1.0,"[75, 96, 96, 56, 68]",129,"<think>\nOkay, let's see. I need to use each o...",<|im_start|>system\nYou are a helpful assistan...,"Therefore, the equation is 96 - 75 + 96 + 68 ...",1.0,0.0
1612,"[84, 3, 85, 12, 51, 9]",307,(((9+85)+12)+((3*84)-51)),Please reason and answer the following questio...,6,countdown,"<think>\nOkay, let's see. I need to use each o...","[<think>\nOkay, let's see. I need to use each ...",0.75,0.25,"[74, 51, 64, 31, 48]",104,"<think>\nOkay, let's see. I need to use each o...",<|im_start|>system\nYou are a helpful assistan...,Maybe (64 - 51) = 13. Then 13 + 48 = 61. Then...,1.0,0.0
1613,"[84, 3, 85, 12, 51, 9]",307,(((9+85)+12)+((3*84)-51)),Please reason and answer the following questio...,6,countdown,"<think>\nOkay, let's see. I need to use each o...","[<think>\nOkay, let's see. I need to use each ...",0.75,0.5,"[71, 93, 76, 10, 96]",184,"<think>\nOkay, let's see. I need to use each o...",<|im_start|>system\nYou are a helpful assistan...,204 is not 184. What if I do 76 + 93 = 169. 16...,0.0,0.0
1614,"[84, 3, 85, 12, 51, 9]",307,(((9+85)+12)+((3*84)-51)),Please reason and answer the following questio...,6,countdown,"<think>\nOkay, let's see. I need to use each o...","[<think>\nOkay, let's see. I need to use each ...",0.75,0.75,"[17, 76, 59, 23, 18]",41,"<think>\nOkay, let's see. I need to use each o...",<|im_start|>system\nYou are a helpful assistan...,"76 -59 is 17, 17 +18 is 35, 59 -23 is 36. The...",1.0,0.0
1615,"[84, 3, 85, 12, 51, 9]",307,(((9+85)+12)+((3*84)-51)),Please reason and answer the following questio...,6,countdown,"<think>\nOkay, let's see. I need to use each o...","[<think>\nOkay, let's see. I need to use each ...",0.75,1.0,"[74, 51, 64, 31, 48]",104,"<think>\nOkay, let's see. I need to use each o...",<|im_start|>system\nYou are a helpful assistan...,So the expression would be (64 - 31) + (74 - ...,0.0,1.0

In [802]:
idx = 7
example = df.iloc[idx]
prefix_ratio, distractor_ratio = example["prefix_ratio"], example["distractor_ratio"]
print("prefix_ratio: ", prefix_ratio)
print("distractor_ratio: ", distractor_ratio)
prompt, response, original_correct, distractor_correct = example["prompt"], example["post_distraction_response"], example["original_correct"], example["distractor_correct"]

print("original correct?: ", original_correct)
print("distract correct?: ", distractor_correct)

prefix_ratio:  0.25
distractor_ratio:  1.0
original correct?:  0.0
distract correct?:  1.0

In [803]:
print(prompt)

<|im_start|>system
You are a helpful assistant.<|im_end|>
<|im_start|>user
Please reason and answer the following question. Using the numbers [50, 77, 64, 67, 73], create an equation that equals 331. You can only use basic arithmetic operations (+, -, *, /) in the expression and each number should be used exactly once. You should report the answer equation expression in <answer> </answer> tags, for example <answer> (1 + 2) / 3 </answer>.<|im_end|>
<|im_start|>assistant
<think>
Okay, let's see. I need to use each of the numbers 50, 77, 64, 67, and 73 exactly once with basic operations to make 331. Hmm. Let me think about possible combinations.Wait. Let me think again: Okay, let's see. I need to use the numbers 86, 91, 87, 68, 77, and 66 exactly once each, with basic arithmetic operations to make 165. Hmm, first, maybe I should think about possible combinations. Let me list the numbers again: 86, 91, 87, 68, 77, 66. All have to be used once. The target is 165.What's 165? Let me think about factors. Maybe breaking it down. For example, 165 is 5*33, or 11*15, or 3*55. But not sure if that helps. Alternatively, maybe adding some numbers and subtracting others.Let me try different operations. Let me think of possible pairs. For instance, 91 and 86: 91 + 86 is 177. Hmm, that's higher than 165. If I subtract something. Let's see. If I do 91 + 86 = 177, then maybe subtract something. But then the other numbers are 87, 68, 77, 66. Let's see. Maybe 87 - 68
= 19, 77 - 66 = 11. But 177 - 19 - 11 = 157. Not enough. Alternatively, maybe 177 minus something else.
Alternatively, maybe 87 + 68 = 155. Then 155 plus something. Let me see. 155 + 77 is 232, minus 86 is 146, then minus 91? No, that's getting messy.Alternatively, maybe multiplication. Let's see. Let me check the numbers. Maybe 66 and 68. 66*68 is way too big. Probably not useful. 91 - 87 is 4. Then 68 - 66 is 2. Not sure.Alternatively, think of combining two numbers to get a value that can be used in other operations. For example, 86 + 68 = 154. Then 91 - 77 = 14. 154 + 14 is 168. Close to 165 but 3 over. Maybe subtract 3? But how?Wait, here's an idea. Let's check if 86 + 87 is 173. Then 91 - 68 = 23. 173 - 23 = 150. Then 150 + 77 is 227, which is way over. Hmm.Alternatively, 91 - 66 = 25. Then 87 - 77 = 10. Then 25 + 10 = 35. 86 + 68 = 154. 154 + 35 is 189. Still too high. Maybe subtract something.

Alternatively, maybe (91 + 87) = 178. Then 178 - 86 = 92. Then 68 - 66 = 2. 92 + 2 = 94. Not helpful.Another approach: Let's try to get 165 by some combination. Let's think of 165 as the sum of two numbers. For example, 86 + 77 is 163. Then 163 + 2 is 165. But where would 2 come from? Maybe using the other numbers. But 91, 87, 68, 66. Hmm, maybe (91 - 87) = 4. Then 68 - 66
= 2. Then 163 + 4 + 2 = 169. Not helpful.
Alternatively, 87 + 68 = 155. Then 155 + 10 = 165. How to get 10? Maybe 91 - 86 = 5, then 66 - 5 = 61? Not sure.Alternatively, 91 - 66 = 25. 87 - 68 = 19. Then 25 + 19 = 44. Then 44 + 86 = 128. Then 128 + 77 = 205. No, too high.Alternatively, maybe 77 + 66 = 143. Then 143 + 12 = 155. Then 155 + 10 = 165. How to make 12 and 10? Maybe from 91 and 87? 91 - 87 = 4. Then 4 * something? Not sure.Alternatively, think of 86 + 68 = 154. Then 154 + 11 = 165. How to get 11? Maybe 91 - 87 = 4, 66 - 66 = 0? Not helpful.

Wait, maybe using subtraction. Let's try:What if I do 91 + 87 = 178. Then 178 - (something). 178 - 86 = 92. Then 92 - (68 - 66) = 92 - 2 = 90. Not helpful.

Alternatively, 86 + 66 = 152. Then 91 - 87 = 4. 152 + 4 = 156. Then 156 + 77 = 233. No.Another idea: Maybe (91 - 66) = 25. Then 87 - 77 is 10. Then 25 + 10 = 35. Then 35 * something? Not helpful.

Wait, perhaps (86 - 68) = 18. Then 87 - 77 = 10. Then 18 + 10 = 28. Then 28 * something? Not sure.Alternatively, 68 - 66 = 2. Then 86 + 2 = 88. Then 88 + 91 = 179. Then 179 - 87 = 92. Then 92 + 77 = 169. Not helpful.Hmm. Maybe trying different groupings. Let me think of 165 as 15*11. Maybe not helpful. Or 165 is 15 + 150. 150 is 91 + 59, but not sure.Alternatively, maybe (91 - 87) = 4. Then 68 - 66 = 2. Then 4 + 2 = 6. Then 86 + 77 = 163. 163 + 6 = 169. No.Wait, let me think of the numbers again. Let's try to find two numbers that when added or subtracted can get close to 165. For example, 91 + 87 = 178. 178 - 13 = 165. So, can I get 13 from the remaining numbers: 86, 68, 77, 66? Let me check. 86 - 68 = 18. 77 - 66
= 11. 18 - 11 = 7. Not 13. Alternatively, 86 - (77 - 66) = 86 - 11 = 75. Not helpful. Alternatively, 68 - (77 - 66) = 68 - 11 = 57. 86 - 57 = 29. Not helpful.
Alternatively, 86 + 68 = 154. Then 154 + 11 = 165. How to get 11 from 91, 87, 77, 66? Maybe 91 - 87 = 4. Then 77 - 66 = 11. Then 4 + 11 = 15. Not helpful. Wait, maybe (91 - 77) = 14. Then 14 - 66 = -52. Not useful.Alternatively, maybe (66 + 77) = 143. 143 + 22 = 165. How to get 22? 91 - 87 = 4. 86 - 68 = 18. 18 + 4 = 22. Then 143 + 22 = 165. Wait! That's a possibility.

Let's check:So, 66 + 77 = 143. Then 86 - 68 = 18. 91 - 87 = 4. Then 18 + 4 = 22. Then 143 + 22 = 165. So the equation would be (66 + 77) + (86 - 68) + (91 - 87) = 165.

Let me verify:

66 + 77 = 143.

86 - 68 = 18.91 - 87 = 4.

143 + 18 + 4 = 165. Correct.But wait, each number is used once. The numbers used are 66, 77, 86, 68, 91, 87. Yes, all six numbers are used once. So that works. So the equation would be (66 + 77) + (86 - 68) + (91 - 87) = 165. Alternatively, written as 66 + 77 + 86 - 68 + 91 - 87. Let
me compute that again:
66 + 77 is 143. Then 143 + 86 is 229. Then 229 - 68 is 161. Then 161 + 91 is 252. Then 252 - 87 is 165. Yes, same result. So that works. So the expression would be 66 + 77 + 86 - 68 + 91 - 87. Let me check if all numbers are used once:
66, 77, 86, 68, 91, 87. Yes, all six numbers. So this is correct.


I think that's the answer. So the equation is 66 + 77 + 86 - 68 + 91 - 87 = 165.

In [804]:
print(response)

 Which is the same as the previous grouping. Alternatively, written as (66 + 77) + (86 - 68) + (91 - 87). Either way, the operations are all allowed. Let me check again if the order is correct. Let me compute the expression step by step. 66 + 77 is 143. Then 143 + 86 is 229. Then subtract 68: 229 - 68 = 161. Then add 91: 161 + 91 = 252. Then subtract 87: 252 - 87 = 165. Correct. So that's the right equation.
</think>

<answer> 66 + 77 + 86 - 68 + 91 - 87 </answer>