In [516]:
import random
from fractions import Fraction
from typing import List, Tuple
import pandas as pd
from datasets import Dataset

import pandas as pd 
import os 

from transformers import AutoModelForCausalLM, AutoTokenizer
from datasets import load_dataset

import seaborn as sns

from datasets import load_dataset, load_from_disk
import numpy as np
import json

from utils.corrupt_num import *
from utils.chunk_r import *

## Evals - How to Scale:
1. number of operands
2. new operations

In [169]:
nums = [ 47, 2, 42, 9, 62, 20, 64 ]
target = 228
question = f"Using the numbers {nums}, create an equation that equals {target}. You can use basic arithmetic operations (+, -, *, /) and each number can only be used once"

In [170]:
tokenizer = AutoTokenizer.from_pretrained("zwhe99/DeepMath-1.5B")

In [171]:
conversations = [
    {"role": "system", "content": "Please reason and answer the following question. You should return the final answer in <answer></answer> tags, for example <answer>(1 + 2) / 3</answer>."},
    {"role": "user", "content": question}
]
prompt = tokenizer.apply_chat_template(
    conversations,
    tokenize=False,
    add_generation_prompt=True
)

In [172]:
print(prompt)

<｜begin▁of▁sentence｜>Please reason and answer the following question. You should return the final answer in <answer></answer> tags, for example <answer>(1 + 2) / 3</answer>.<｜User｜>Using the numbers [47, 2, 42, 9, 62, 20, 64], create an equation that equals 228. You can use basic arithmetic operations (+, -, *, /) and each number can only be used once<｜Assistant｜><think>

In [ ]:
"Please reason and answer the following question. At the end, you should return the final answer in <answer></answer> tags, for example <answer>(1 + 2) / 3</answer>. Using the numbers {nums}, create an equation that equals {target}. You can use basic arithmetic operations (+, -, *, /) in the expression and each number can only be used once."

In [173]:
47 + 62 + 9 + 64 + 42/2

203.0

# Check Eval Dataset

In [828]:
cd /home/al2644/research/codebase/reasoning/perturb-r/

/home/al2644/research/codebase/reasoning/perturb-r

In [816]:
path = "./data/train/countdown_level45_20k/train.parquet"
df = pd.read_parquet(path)

In [819]:
df["prompt"][0]

array([{'content': 'Please reason and answer the following question. Using the numbers [50, 34, 97, 68], create an equation that equals 181. You can only use basic arithmetic operations (+, -, *, /) in the expression and each number should be used exactly once. You should report the answer equation expression in <answer> </answer> tags, for example <answer> (1 + 2) / 3 </answer>.', 'role': 'user'}],
      dtype=object)

In [823]:
def format_dataset(row, tokenizer = tokenizer):
    problem = row['problem']
    response = row['response']
    conversation = [
        {"role": "user", "content": problem},
        {"role": "assistant", "content": response}
    ]

    return tokenizer.apply_chat_template(conversation, tokenize=False)

In [383]:
result = format_dataset(row)

# Reasoning Benchmark Eval

In [837]:
root = "./results/countdown/benchmark/"
tokenizer = AutoTokenizer.from_pretrained('Qwen/Qwen2.5-3B')
for fname in os.listdir(root):
    if 'correct' not in fname:
        print(fname)
        df = pd.read_pickle(os.path.join(root, fname))
        print(f"Accuracy: {df['correct'].mean()}")

# model specific
df = pd.read_pickle(os.path.join(root, 'Qwen2.5-3B-grpo-countdown-level4-5-1epoch.pickle'))

Qwen2.5-3B-distill-countdown-level3-4-1epoch.pickle
Accuracy: 0.24214285714285713
Qwen2.5-3B-distill-countdown-level3-4-3epoch.pickle
Accuracy: 0.24714285714285714
Qwen2.5-3B-grpo-countdown-level4-5-1epoch.pickle
Accuracy: 0.35

In [612]:
def groupby_level (df):
    stats = df.groupby('level')['correct'].mean()
    return stats

In [835]:
groupby_level(df)

level
4     0.890
5     0.550
6     0.205
7     0.050
9     0.000
11    0.000
13    0.000
Name: correct, dtype: float64

In [838]:
groupby_level(df)

level
4     0.935
5     0.745
6     0.450
7     0.310
9     0.010
11    0.000
13    0.000
Name: correct, dtype: float64

# Corrupted Numbers

In [840]:
pwd

'/home/al2644/research/codebase/reasoning/perturb-r'

In [841]:
root = "./results/countdown/corrupt_numbers/"

def has_answer (response):
    if "<answer>" in response:
        return 1.
    else:
        return 0.
    
for fname in os.listdir(root):
    if 'still_correct' not in fname:
        print(fname)
        df = pd.read_pickle(os.path.join(root, fname))
        print(f"Accuracy: {df['still_correct'].mean()}")

Qwen2.5-3B-distill-countdown-level3-4-1epoch.pickle
Accuracy: 0.5202702702702703
Qwen2.5-3B-grpo-countdown-level4-5-1epoch.pickle
Accuracy: 0.5934684684684685

In [842]:
df = pd.read_pickle(os.path.join(root, "Qwen2.5-3B-grpo-countdown-level4-5-1epoch.pickle"))

In [844]:
df.groupby("start_pos")["still_correct"].mean()

start_pos
0.00    0.184685
0.25    0.720721
0.50    0.752252
0.75    0.716216
Name: still_correct, dtype: float64

In [854]:
df.groupby("start_pos")["if_answer"].mean()

start_pos
0.00    0.409910
0.25    0.765766
0.50    0.788288
0.75    0.995495
Name: if_answer, dtype: float64

In [858]:
example = df[(df["start_pos"] == 0.5) & (df["still_correct"] == 0.) & (df["if_answer"] == True)].iloc[0]

In [859]:
print(example["prompt"])

<|im_start|>system
You are a helpful assistant.<|im_end|>
<|im_start|>user
Please reason and answer the following question. Using the numbers [13, 10, 27, 92, 31], create an equation that equals 742. You can only use basic arithmetic operations (+, -, *, /) in the expression and each number should be used exactly once. You should report the answer equation expression in <answer> </answer> tags, for example <answer> (1 + 2) / 3 </answer>.<|im_end|>
<|im_start|>assistant
<think>


Okay, let's see. I need to use the numbers 13, 10, 27, 92, and 31 exactly once each, with basic operations to make 742. Hmm. Let me think. First, maybe I should try combining some numbers to get closer to 742. Since 742 is a relatively large number, maybe multiplication is involved here. Let me check the numbers: 92 is


the largest, then 31, 27, 10, 13.


Let me think about possible multiplications. If I multiply 92 by something, maybe? Let's see. 92 * 8 is 736, which is close to 742. But how do I get 8 from the other numbers? The remaining numbers are 13, 10, 27, 31. Wait, but I need to use all numbers once. Maybe that approach is not working. Alternatively, maybe


31 * something?


Alternatively, let's think of 742 divided by some numbers. For example, 742 divided by 13 is about 57. The other numbers would be 10, 27, 92, 31. Hmm. Not sure. Maybe 742 divided by 27? That's around 27.48, not helpful.

Alternatively, perhaps combining two numbers through addition or subtraction first. For instance, 92 + 31 = 123. Then maybe 123 * something? Let's see. 123 * 6 is 738, which is close. Then 738 + 4 would be 742. But how to get 6 and 4 from the remaining numbers 13, 10, 27? Not sure.

Alternatively, maybe 27 * 10 = 270. Then 270 * something? If I have 270 * 2.74... but that's not helpful. Maybe not. Another thought: 13 * 10 = 13. Then 13 * something? 13 * 5.7 is 71. That's close. But again, how to get 5.7 from 2, 2, 13? Maybe not.

Alternatively, maybe 2 * 13 is a big number. 2*13 is 2825. That's way too big. Maybe subtract something? 2825 minus 10 is 2482, minus 2 is 28115, minus 13 is 202. Not helpful.

Alternatively, 2 * 10 is 29. Then 29 minus something. 29 - 2 = 8933, 8933 - 13 = 682, 682 - 13 is 8499. Not 724.

Wait, maybe 2 * 13 is 120. That's bigger than 724. 120 minus something. 120 - 2 = 11112, then 11112 - 13 = 10811, then 10811 - 2 = 10544. No, not helpful.

Alternatively, 13 * 10 = 10. 10 + 2 = 37. Then 2 * 13 is 120. 120 + 37 is 141. Nope. Not helpful.

In [860]:
print(example["post_corruption_response"])

Alternatively, think of 92 * 10 = 920. Then 920 - 27 = 893. 893 - 13 = 880. 880 + 31 = 911. No, that's not helpful.

Alternatively, 92 * 27 = 2484. Then 2484 - 31 = 2453. 2453 - 13 = 2440. 2440 + 10 = 2450. Not 742.

Alternatively, 92 * 13 = 1204. Then 1204 - 31 = 1173. 1173 - 27 = 1146. 1146 - 10 = 1136. That's way over.

Alternatively, 92 * 31 = 2852. Then 2852 - 27 = 2825. 2825 - 13 = 2812. 2812 - 10 = 2802. No.

Alternatively, 31 * 10 = 310. Then 310 + 27 = 337. 337 + 92 = 429. 429 + 13 = 442. No.

Wait, maybe 27 * 13 = 351. Then 351 * 2 = 702. Then 702 + 40 = 742. How to get 40 from 92 and 31. 92 - 31 = 61. Not 40. 92 - 31 is 61, then 61 - 10 = 51. No.

Alternatively, 27 * 10 = 270. Then 270 + 92 = 362. 362 * something? 362 * 2 is 724. Then 724 + 18 = 742. How to get 18 from 13 and 31. 31 - 13 = 18. Oh! Wait! That's possible.

So let's see: (27 * 10) + 92 = 362. Then 362 + (31 - 13) = 362 + 18 = 380. No, that's not. Wait, but if I do 27 * 10 + 92 + (31 -13) = 362 + 92 + 18 = 572. Not helpful.

Alternatively, maybe (27 * 10) + 92 + (31 - 13) = 362 + 92 + 18 = 572. No.

Wait, but if I do 27 * 10 = 270, then 270 + 92 = 362. Then 362 + (31 - 13) = 362 + 18 = 380. Not helpful.

Alternatively, if I do 31 - 13 = 18, then 27 * 10 = 270. 270 + 18 = 288. Then 288 + 92 = 380. Still not.

Alternatively, maybe 31 + 13 = 44. Then 44 * 10 = 440. Then 440 + 92 = 532. 532 + 27 = 559. Not helpful.

Alternatively, 92 - 31 = 61. 61 * 10 = 610. 610 + 27 = 637. 637 + 13 = 650. No.

Hmm. Maybe another approach. Let me think. 742 divided by 92 is about 8.05. So maybe 8 * 92 is 736. Then 736 + 6 = 742. How to get 6 from 13, 10, 27, 31. 31 - 27 = 4, 13 - 10 = 3. 4 + 3 = 7. Not 6. Alternatively, 13 - (31 - 27) = 13 - 4 = 9. Hmm. Maybe not.

Alternatively, 742 divided by 27 is about 27.48. Maybe not.

Alternatively, 742 divided by 13 is 57. So if I can get 57 from the other numbers, then 13 * 57 = 742. But how? The numbers left are 10, 27, 92, 31. How to make 57? Let's see. For example, 92 - 31 = 61. 61 - 27 = 34. 34 + 10 = 44. Not 57. Or 31 + 10 = 41. 41 + 27 = 68. 68 - 92 = -24. Not helpful.

Alternatively, 27 + 10 = 37. 37 + 92 = 129. 129 - 31 = 98. No.

Alternatively, 92 - 31 = 61. 61 - 10 = 51. 51 + 27 = 78. 78 - 13 = 65. Not 57.

Alternatively, 10 * 27 = 270. 270 + 31 = 301. 301 + 92 = 393. 393 + 13 = 406. No.

Alternatively, 10 * 31 = 310. 310 + 92 = 402. 402 + 27 = 429. 429 + 13 = 442. Not helpful.

Another angle: Maybe 31 * 10 = 310. Then 310 + 92 = 402. 402 + 27 = 429. 429 + 13 = 442. Not enough. But 442 + 70 = 512, which is not helpful.

Alternatively, 27 * 13 = 351. 351 + 92 = 443. 443 + 31 = 474. 474 + 10 = 484. No.

Alternatively, 92 * 10 = 920. Then 920 - 31 = 889. 889 - 27 = 862. 862 - 13 = 849. Close to 742. 849 - 10 = 839. Not helpful.

Alternatively, 92 * 10 is 920. Then 920 - 31 = 889. Then 889 - 27 = 862. Then 862 - 13 = 849. Then 849 - 10 = 839. Still not.

Alternatively, 92 * 13 = 1204. Then 1204 - 31 = 1173. Then 1173 - 27 = 1146. 1146 - 10 = 1136. No.

Alternatively, 31 * 27 = 837. Then 837 - 10 = 827. 827 - 13 = 814. 814 + 92 = 906. No.

Alternatively, 10 * 27 = 270. 270 + 92 = 362. 362 + 31 = 393. 393 + 13 = 406. Not helpful.

Alternatively, 13 * 10 = 130. 130 + 27 = 157. 157 + 92 = 249. 249 + 31 = 280. No.

Alternative approach: Maybe combining numbers in a different way. Let's think of 742 as 700 + 42. How to get that. Maybe 92 * 8 = 744, which is 742 + 2. Then if I can do 92 * 8 - 2 = 742. How to get 8 and 2 from the remaining numbers? 13, 10, 27, 31. Wait, but that's not straightforward.

Alternatively, maybe 92 * 8 + 50 = 742. But how to get 8 and 50? Maybe not.

Alternatively, maybe (something) * (something else) + (something else).

Alternatively, 27 * 31 = 837. 837 - 10 = 827. 827 + 92 = 919. 919 - 13 = 906. No.

Alternatively, 92 * 10 = 920. 920 - 27 = 893. 893 - 31 = 862. 862 - 13 = 849. Still not.

Wait, but earlier thought of 31 - 13 = 18, and 27 * 10 = 270, then 270 + 18 = 288, 288 + 92 = 380. Not helpful.

Alternatively, maybe 27 * (something) + something else.

Alternatively, 31 * 10 = 310. Then 310 + 92 = 402. 402 + 27 = 429. 429 + 13 = 442. Then 442 + 70 = 512. No.

Alternatively, 31 * 10 = 310. 310 + 92 = 402. Then 402 + 27 = 429. 429 + 13 = 442. Then 442 + 10 = 452. No.

Alternatively, 27 * 13 = 351. 351 + 92 = 443. 443 + 31 = 474. 474 + 10 = 484. No.

Alternatively, 27 * 2 = 54. 54 + 92 = 146. 146 + 31 = 177. 177 + 10 = 187. No.

Alternatively, 10 * 13 = 130. 130 + 92 = 222. 222 + 27 = 249. 249 + 31 = 280. No.

Another thought: Maybe (92 + 13) = 105. Then 105 * 7 = 735. 735 + 7 = 742. But how to get 7? 27 - (31 - 10) = 27 - 21 = 6. Not 7. Alternatively, 31 - (27 + 10) = 31 - 37 = -6. Not helpful.

Alternatively, 92 - 13 = 79. 79 * 10 = 790. 790 - 27 = 763. 763 - 31 = 732. 732 + 10 = 742! Wait! Wait, that's possible. Let me check that again.

So 92 - 13 = 79. Then 79 * 10 = 790. Then 790 -27 = 763. Then 763 - 31 = 732. Then 732 + 10 = 742. But wait, that would use all numbers once? Let's check. The numbers used are 92, 13, 10, 27, 31. Yes, each is used once.

So the equation would be ((92 - 13) * 10) - 27 - 31 + 10? Wait, but that would be ((92 - 13) * 10) - 27 - 31 + 10? But that would be 79*10 = 790, then 790 -27 is 763, then 763 -31 is 732, then 732 +10 is 742. Yes! But let me check the order of operations.

Wait, if it's ((92 - 13) * 10) - 27 - 31 + 10, that would be (79 * 10) -27 -31 +10. Which is 790 -27 = 763, 763 -31 = 732, 732 +10 = 742. So that works.

But let me check if that uses all numbers once. 92, 13, 10, 27, 31. Yes. Each is used once.

So the expression would be ((92 - 13) * 10) - 27 - 31 + 10. But maybe I can write it as (92 - 13) * 10 - 27 - 31 + 10.

Alternatively, maybe other combinations. Let me check if that's correct.

Yes, that seems to work. Let me verify the calculation again.

92 - 13 = 79. 79 * 10 = 790. Then 790 - 27 = 763. Then 763 - 31 = 732. Then 732 + 10 = 742. Correct.

So that's the equation. Therefore, the answer is ((92 - 13) * 10) - 27 - 31 + 10.

Alternatively, written as (92 - 13) * 10 - 27 - 31 + 10.

But maybe the order of operations would be okay. Let me check if that's the case.

Alternatively, maybe I can write it as 92 * 10 - 13 * 10 + 92 - 31 + 10. Wait, that would be 920 - 130 + 92 - 31 +10. Which is 920 -130 is 790, 790 +92 is 882, 882 -31 is 851, 851 +10 is 861. No, that's not correct.

Alternatively, (92 - 13) * 10 - 27 - 31 + 10.

Yes, that's the correct expression.

So the answer should be that expression. Let me make sure that all numbers are used once: 92, 13, 10, 27, 31. Yes.

Therefore, the correct equation is (92 - 13) * 10 - 27 - 31 + 10 = 742.

Alternatively, maybe there's another way, but this seems to work. So that's the solution.
</think>

<answer> (92 - 13) * 10 - 27 - 31 + 10 </answer>

In [695]:
wrong_answer[['level', 'type']].value_counts()

level  type
5      post_</think>    80
6      post_</think>    21
5      pre_</think>     17
6      pre_</think>      5
Name: count, dtype: int64

# Distractor Injection

In [796]:
root = "./results/countdown/inject_distractor/"

def has_answer (response):
    if "<answer>" in response:
        return 1.
    else:
        return 0.
    
for fname in os.listdir(root):
    print(fname)
    df = pd.read_pickle(os.path.join(root, fname))
    print(f"Original Accuracy: {df['original_correct'].mean()}")
    print(f"Distractor Accuracy: {df['distractor_correct'].mean()}")

df = pd.read_pickle(os.path.join(root, "Qwen2.5-3B-grpo-countdown-level4-5-1epoch.pickle"))

Qwen2.5-3B-distill-countdown-level3-4-1epoch.pickle
Original Accuracy: 0.3626237623762376
Distractor Accuracy: 0.5006188118811881
Qwen2.5-3B-grpo-countdown-level4-5-1epoch.pickle
Original Accuracy: 0.46163366336633666
Distractor Accuracy: 0.47277227722772275

In [797]:
df = pd.read_pickle(os.path.join(root, "Qwen2.5-3B-distill-countdown-level3-4-1epoch.pickle"))
df.groupby("prefix_ratio")[["original_correct", "distractor_correct"]].mean()

              original_correct  distractor_correct
prefix_ratio
0.00                  0.047030            0.816832
0.25                  0.544554            0.292079
0.50                  0.462871            0.400990
0.75                  0.396040            0.492574

In [798]:
df = pd.read_pickle(os.path.join(root, "Qwen2.5-3B-grpo-countdown-level4-5-1epoch.pickle"))
df.groupby("prefix_ratio")[["original_correct", "distractor_correct"]].mean()

              original_correct  distractor_correct
prefix_ratio
0.00                  0.009901            0.938119
0.25                  0.670792            0.252475
0.50                  0.613861            0.309406
0.75                  0.551980            0.391089

In [799]:
df

,nums,target,example_solution,problem,level,task,original_response,reasoning_chunks,prefix_ratio,distractor_ratio,distract_nums,distract_target,distract_reasoning,prompt,post_distraction_response,original_correct,distractor_correct
0,"[50, 77, 64, 67, 73]",331,(((73+50)+64)+(67+77)),Please reason and answer the following questio...,5,countdown,"<think>\nOkay, let's see. I need to use each o...","[<think>\nOkay, let's see. I need to use each ...",0.0,0.25,"[86, 91, 87, 68, 77, 66]",165,"<think>\nOkay, let's see. I need to use the nu...",<|im_start|>system\nYou are a helpful assistan...,"Not sure. Alternatively, 87 - 66 = 21. 91 - 7...",0.0,1.0
1,"[50, 77, 64, 67, 73]",331,(((73+50)+64)+(67+77)),Please reason and answer the following questio...,5,countdown,"<think>\nOkay, let's see. I need to use each o...","[<think>\nOkay, let's see. I need to use each ...",0.0,0.5,"[20, 73, 85, 82, 33]",89,"<think>\nOkay, let's see. I need to use the nu...",<|im_start|>system\nYou are a helpful assistan...,33 + 85 is 118. 118 - 82 is 36. 36 +73 is 109...,0.0,1.0
2,"[50, 77, 64, 67, 73]",331,(((73+50)+64)+(67+77)),Please reason and answer the following questio...,5,countdown,"<think>\nOkay, let's see. I need to use each o...","[<think>\nOkay, let's see. I need to use each ...",0.0,0.75,"[20, 73, 85, 82, 33]",89,"<think>\nOkay, let's see. I need to use the nu...",<|im_start|>system\nYou are a helpful assistan...,So the answer would be that expression. So th...,0.0,1.0
3,"[50, 77, 64, 67, 73]",331,(((73+50)+64)+(67+77)),Please reason and answer the following questio...,5,countdown,"<think>\nOkay, let's see. I need to use each o...","[<think>\nOkay, let's see. I need to use each ...",0.0,1.0,"[74, 51, 64, 31, 48]",104,"<think>\nOkay, let's see. I need to use the nu...",<|im_start|>system\nYou are a helpful assistan...,The answer should be in <answer> tags. So <an...,0.0,1.0
4,"[50, 77, 64, 67, 73]",331,(((73+50)+64)+(67+77)),Please reason and answer the following questio...,5,countdown,"<think>\nOkay, let's see. I need to use each o...","[<think>\nOkay, let's see. I need to use each ...",0.25,0.25,"[25, 87, 42, 34, 57]",63,"<think>\nOkay, let's see. I need to use each o...",<|im_start|>system\nYou are a helpful assistan...,"87 - 57 is 30, then 30 - 25 is 5, not helpful....",1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1611,"[84, 3, 85, 12, 51, 9]",307,(((9+85)+12)+((3*84)-51)),Please reason and answer the following questio...,6,countdown,"<think>\nOkay, let's see. I need to use each o...","[<think>\nOkay, let's see. I need to use each ...",0.5,1.0,"[75, 96, 96, 56, 68]",129,"<think>\nOkay, let's see. I need to use each o...",<|im_start|>system\nYou are a helpful assistan...,"Therefore, the equation is 96 - 75 + 96 + 68 ...",1.0,0.0
1612,"[84, 3, 85, 12, 51, 9]",307,(((9+85)+12)+((3*84)-51)),Please reason and answer the following questio...,6,countdown,"<think>\nOkay, let's see. I need to use each o...","[<think>\nOkay, let's see. I need to use each ...",0.75,0.25,"[74, 51, 64, 31, 48]",104,"<think>\nOkay, let's see. I need to use each o...",<|im_start|>system\nYou are a helpful assistan...,Maybe (64 - 51) = 13. Then 13 + 48 = 61. Then...,1.0,0.0
1613,"[84, 3, 85, 12, 51, 9]",307,(((9+85)+12)+((3*84)-51)),Please reason and answer the following questio...,6,countdown,"<think>\nOkay, let's see. I need to use each o...","[<think>\nOkay, let's see. I need to use each ...",0.75,0.5,"[71, 93, 76, 10, 96]",184,"<think>\nOkay, let's see. I need to use each o...",<|im_start|>system\nYou are a helpful assistan...,204 is not 184. What if I do 76 + 93 = 169. 16...,0.0,0.0
1614,"[84, 3, 85, 12, 51, 9]",307,(((9+85)+12)+((3*84)-51)),Please reason and answer the following questio...,6,countdown,"<think>\nOkay, let's see. I need to use each o...","[<think>\nOkay, let's see. I need to use each ...",0.75,0.75,"[17, 76, 59, 23, 18]",41,"<think>\nOkay, let's see. I need to use each o...",<|im_start|>system\nYou are a helpful assistan...,"76 -59 is 17, 17 +18 is 35, 59 -23 is 36. The...",1.0,0.0
1615,"[84, 3, 85, 12, 51, 9]",307,(((9+85)+12)+((3*84)-51)),Please reason and answer the following questio...,6,countdown,"<think>\nOkay, let's see. I need to use each o...","[<think>\nOkay, let's see. I need to use each ...",0.75,1.0,"[74, 51, 64, 31, 48]",104,"<think>\nOkay, let's see. I need to use each o...",<|im_start|>system\nYou are a helpful assistan...,So the expression would be (64 - 31) + (74 - ...,0.0,1.0

In [802]:
idx = 7
example = df.iloc[idx]
prefix_ratio, distractor_ratio = example["prefix_ratio"], example["distractor_ratio"]
print("prefix_ratio: ", prefix_ratio)
print("distractor_ratio: ", distractor_ratio)
prompt, response, original_correct, distractor_correct = example["prompt"], example["post_distraction_response"], example["original_correct"], example["distractor_correct"]

print("original correct?: ", original_correct)
print("distract correct?: ", distractor_correct)

prefix_ratio:  0.25
distractor_ratio:  1.0
original correct?:  0.0
distract correct?:  1.0

In [803]:
print(prompt)

<|im_start|>system
You are a helpful assistant.<|im_end|>
<|im_start|>user
Please reason and answer the following question. Using the numbers [50, 77, 64, 67, 73], create an equation that equals 331. You can only use basic arithmetic operations (+, -, *, /) in the expression and each number should be used exactly once. You should report the answer equation expression in <answer> </answer> tags, for example <answer> (1 + 2) / 3 </answer>.<|im_end|>
<|im_start|>assistant
<think>
Okay, let's see. I need to use each of the numbers 50, 77, 64, 67, and 73 exactly once with basic operations to make 331. Hmm. Let me think about possible combinations.Wait. Let me think again: Okay, let's see. I need to use the numbers 86, 91, 87, 68, 77, and 66 exactly once each, with basic arithmetic operations to make 165. Hmm, first, maybe I should think about possible combinations. Let me list the numbers again: 86, 91, 87, 68, 77, 66. All have to be used once. The target is 165.What's 165? Let me think about factors. Maybe breaking it down. For example, 165 is 5*33, or 11*15, or 3*55. But not sure if that helps. Alternatively, maybe adding some numbers and subtracting others.Let me try different operations. Let me think of possible pairs. For instance, 91 and 86: 91 + 86 is 177. Hmm, that's higher than 165. If I subtract something. Let's see. If I do 91 + 86 = 177, then maybe subtract something. But then the other numbers are 87, 68, 77, 66. Let's see. Maybe 87 - 68
= 19, 77 - 66 = 11. But 177 - 19 - 11 = 157. Not enough. Alternatively, maybe 177 minus something else.
Alternatively, maybe 87 + 68 = 155. Then 155 plus something. Let me see. 155 + 77 is 232, minus 86 is 146, then minus 91? No, that's getting messy.Alternatively, maybe multiplication. Let's see. Let me check the numbers. Maybe 66 and 68. 66*68 is way too big. Probably not useful. 91 - 87 is 4. Then 68 - 66 is 2. Not sure.Alternatively, think of combining two numbers to get a value that can be used in other operations. For example, 86 + 68 = 154. Then 91 - 77 = 14. 154 + 14 is 168. Close to 165 but 3 over. Maybe subtract 3? But how?Wait, here's an idea. Let's check if 86 + 87 is 173. Then 91 - 68 = 23. 173 - 23 = 150. Then 150 + 77 is 227, which is way over. Hmm.Alternatively, 91 - 66 = 25. Then 87 - 77 = 10. Then 25 + 10 = 35. 86 + 68 = 154. 154 + 35 is 189. Still too high. Maybe subtract something.

Alternatively, maybe (91 + 87) = 178. Then 178 - 86 = 92. Then 68 - 66 = 2. 92 + 2 = 94. Not helpful.Another approach: Let's try to get 165 by some combination. Let's think of 165 as the sum of two numbers. For example, 86 + 77 is 163. Then 163 + 2 is 165. But where would 2 come from? Maybe using the other numbers. But 91, 87, 68, 66. Hmm, maybe (91 - 87) = 4. Then 68 - 66
= 2. Then 163 + 4 + 2 = 169. Not helpful.
Alternatively, 87 + 68 = 155. Then 155 + 10 = 165. How to get 10? Maybe 91 - 86 = 5, then 66 - 5 = 61? Not sure.Alternatively, 91 - 66 = 25. 87 - 68 = 19. Then 25 + 19 = 44. Then 44 + 86 = 128. Then 128 + 77 = 205. No, too high.Alternatively, maybe 77 + 66 = 143. Then 143 + 12 = 155. Then 155 + 10 = 165. How to make 12 and 10? Maybe from 91 and 87? 91 - 87 = 4. Then 4 * something? Not sure.Alternatively, think of 86 + 68 = 154. Then 154 + 11 = 165. How to get 11? Maybe 91 - 87 = 4, 66 - 66 = 0? Not helpful.

Wait, maybe using subtraction. Let's try:What if I do 91 + 87 = 178. Then 178 - (something). 178 - 86 = 92. Then 92 - (68 - 66) = 92 - 2 = 90. Not helpful.

Alternatively, 86 + 66 = 152. Then 91 - 87 = 4. 152 + 4 = 156. Then 156 + 77 = 233. No.Another idea: Maybe (91 - 66) = 25. Then 87 - 77 is 10. Then 25 + 10 = 35. Then 35 * something? Not helpful.

Wait, perhaps (86 - 68) = 18. Then 87 - 77 = 10. Then 18 + 10 = 28. Then 28 * something? Not sure.Alternatively, 68 - 66 = 2. Then 86 + 2 = 88. Then 88 + 91 = 179. Then 179 - 87 = 92. Then 92 + 77 = 169. Not helpful.Hmm. Maybe trying different groupings. Let me think of 165 as 15*11. Maybe not helpful. Or 165 is 15 + 150. 150 is 91 + 59, but not sure.Alternatively, maybe (91 - 87) = 4. Then 68 - 66 = 2. Then 4 + 2 = 6. Then 86 + 77 = 163. 163 + 6 = 169. No.Wait, let me think of the numbers again. Let's try to find two numbers that when added or subtracted can get close to 165. For example, 91 + 87 = 178. 178 - 13 = 165. So, can I get 13 from the remaining numbers: 86, 68, 77, 66? Let me check. 86 - 68 = 18. 77 - 66
= 11. 18 - 11 = 7. Not 13. Alternatively, 86 - (77 - 66) = 86 - 11 = 75. Not helpful. Alternatively, 68 - (77 - 66) = 68 - 11 = 57. 86 - 57 = 29. Not helpful.
Alternatively, 86 + 68 = 154. Then 154 + 11 = 165. How to get 11 from 91, 87, 77, 66? Maybe 91 - 87 = 4. Then 77 - 66 = 11. Then 4 + 11 = 15. Not helpful. Wait, maybe (91 - 77) = 14. Then 14 - 66 = -52. Not useful.Alternatively, maybe (66 + 77) = 143. 143 + 22 = 165. How to get 22? 91 - 87 = 4. 86 - 68 = 18. 18 + 4 = 22. Then 143 + 22 = 165. Wait! That's a possibility.

Let's check:So, 66 + 77 = 143. Then 86 - 68 = 18. 91 - 87 = 4. Then 18 + 4 = 22. Then 143 + 22 = 165. So the equation would be (66 + 77) + (86 - 68) + (91 - 87) = 165.

Let me verify:

66 + 77 = 143.

86 - 68 = 18.91 - 87 = 4.

143 + 18 + 4 = 165. Correct.But wait, each number is used once. The numbers used are 66, 77, 86, 68, 91, 87. Yes, all six numbers are used once. So that works. So the equation would be (66 + 77) + (86 - 68) + (91 - 87) = 165. Alternatively, written as 66 + 77 + 86 - 68 + 91 - 87. Let
me compute that again:
66 + 77 is 143. Then 143 + 86 is 229. Then 229 - 68 is 161. Then 161 + 91 is 252. Then 252 - 87 is 165. Yes, same result. So that works. So the expression would be 66 + 77 + 86 - 68 + 91 - 87. Let me check if all numbers are used once:
66, 77, 86, 68, 91, 87. Yes, all six numbers. So this is correct.


I think that's the answer. So the equation is 66 + 77 + 86 - 68 + 91 - 87 = 165.

In [804]:
print(response)

 Which is the same as the previous grouping. Alternatively, written as (66 + 77) + (86 - 68) + (91 - 87). Either way, the operations are all allowed. Let me check again if the order is correct. Let me compute the expression step by step. 66 + 77 is 143. Then 143 + 86 is 229. Then subtract 68: 229 - 68 = 161. Then add 91: 161 + 91 = 252. Then subtract 87: 252 - 87 = 165. Correct. So that's the right equation.
</think>

<answer> 66 + 77 + 86 - 68 + 91 - 87 </answer>

In [ ]:
DataProto(batch=TensorDict(
    fields={
        attention_mask: Tensor(shape=torch.Size([6, 256]), device=cpu, dtype=torch.int64, is_shared=False),
        input_ids: Tensor(shape=torch.Size([6, 256]), device=cpu, dtype=torch.int64, is_shared=False),
        position_ids: Tensor(shape=torch.Size([6, 256]), device=cpu, dtype=torch.int64, is_shared=False)},
    batch_size=torch.Size([6]),
    device=None,
    is_shared=False), non_tensor_batch={}, meta_info={})

In [ ]:
max_prompt_length = max([len(tokenizer.encode(seq)) for seq in corrupt_sequences])

In [ ]:
ipdb> batch
DataProto(batch=TensorDict(
    fields={
        attention_mask: Tensor(shape=torch.Size([6, 256]), device=cpu, dtype=torch.int64, is_shared=False),
        input_ids: Tensor(shape=torch.Size([6, 256]), device=cpu, dtype=torch.int64, is_shared=False),
        position_ids: Tensor(shape=torch.Size([6, 256]), device=cpu, dtype=torch.int64, is_shared=False)},
    batch_size=torch.Size([6]),
    device=None,
    is_shared=False), non_tensor_batch={'data_source': array(['countdown', 'countdown', 'countdown', 'countdown', 'countdown',
       'countdown'], dtype=object), 'ability': array(['math', 'math', 'math', 'math', 'math', 'math'], dtype=object), 'reward_model': array([{'ground_truth': {'numbers': array([ 9, 48, 98, 52, 39]), 'target': 46}, 'style': 'rule'},
       {'ground_truth': {'numbers': array([54,  5,  8, 25, 14]), 'target': 90}, 'style': 'rule'},
       {'ground_truth': {'numbers': array([15, 10, 59, 96,  1]), 'target': 800}, 'style': 'rule'},
       {'ground_truth': {'numbers': array([ 8,  1,  1, 29]), 'target': 290}, 'style': 'rule'},
       {'ground_truth': {'numbers': array([71, 85,  9, 79, 40]), 'target': 49}, 'style': 'rule'},
       {'ground_truth': {'numbers': array([32, 21, 50, 45]), 'target': 42}, 'style': 'rule'}],
      dtype=object), 'extra_info': array([{'index': 15845, 'level': '5', 'split': 'train'},
       {'index': 10294, 'level': '5', 'split': 'train'},
       {'index': 19532, 'level': '5', 'split': 'train'},
       {'index': 4256, 'level': '4', 'split': 'train'},
       {'index': 11363, 'level': '5', 'split': 'train'},
       {'index': 7923, 'level': '4', 'split': 'train'}], dtype=object), 'index': array([15845, 10294, 19532, 4256, 11363, 7923], dtype=object)}, meta_info={})

In [ ]:
DataProtoItem(batch=TensorDict(
    fields={
        attention_mask: Tensor(shape=torch.Size([11, 4352]), device=cpu, dtype=torch.int64, is_shared=False),
        input_ids: Tensor(shape=torch.Size([11, 4352]), device=cpu, dtype=torch.int64, is_shared=False),
        old_log_probs: Tensor(shape=torch.Size([11, 4096]), device=cpu, dtype=torch.float32, is_shared=False),
        position_ids: Tensor(shape=torch.Size([11, 4352]), device=cpu, dtype=torch.int64, is_shared=False),
        prompts: Tensor(shape=torch.Size([11, 256]), device=cpu, dtype=torch.int64, is_shared=False),
        ref_log_prob: Tensor(shape=torch.Size([11, 4096]), device=cpu, dtype=torch.float32, is_shared=False),
        responses: Tensor(shape=torch.Size([11, 4096]), device=cpu, dtype=torch.int64, is_shared=False),
        token_level_scores: Tensor(shape=torch.Size([11, 4096]), device=cpu, dtype=torch.float32, is_shared=False)},
    batch_size=torch.Size([11]),
    device=None,
    is_shared=False), non_tensor_batch={'data_source': array(['countdown', 'countdown', 'countdown', 'countdown', 'countdown',
       'countdown', 'countdown', 'countdown', 'countdown', 'countdown',
       'countdown'], dtype=object), 'ability': array(['math', 'math', 'math', 'math', 'math', 'math', 'math', 'math',
       'math', 'math', 'math'], dtype=object), 'reward_model': array([{'ground_truth': {'numbers': array([ 9, 48, 98, 52, 39]), 'target': 46}, 'style': 'rule'},
       {'ground_truth': {'numbers': array([ 9, 48, 98, 52, 39]), 'target': 46}, 'style': 'rule'},
       {'ground_truth': {'numbers': array([ 9, 48, 98, 52, 39]), 'target': 46}, 'style': 'rule'},
       {'ground_truth': {'numbers': array([54,  5,  8, 25, 14]), 'target': 90}, 'style': 'rule'},
       {'ground_truth': {'numbers': array([54,  5,  8, 25, 14]), 'target': 90}, 'style': 'rule'},
       {'ground_truth': {'numbers': array([ 8,  1,  1, 29]), 'target': 290}, 'style': 'rule'},
       {'ground_truth': {'numbers': array([ 8,  1,  1, 29]), 'target': 290}, 'style': 'rule'},
       {'ground_truth': {'numbers': array([ 8,  1,  1, 29]), 'target': 290}, 'style': 'rule'},
       {'ground_truth': {'numbers': array([32, 21, 50, 45]), 'target': 42}, 'style': 'rule'},
       {'ground_truth': {'numbers': array([32, 21, 50, 45]), 'target': 42}, 'style': 'rule'},
       {'ground_truth': {'numbers': array([32, 21, 50, 45]), 'target': 42}, 'style': 'rule'}],
      dtype=object), 'extra_info': array([{'index': 15845, 'level': '5', 'split': 'train'},
       {'index': 15845, 'level': '5', 'split': 'train'},
       {'index': 15845, 'level': '5', 'split': 'train'},
       {'index': 10294, 'level': '5', 'split': 'train'},
       {'index': 10294, 'level': '5', 'split': 'train'},
       {'index': 4256, 'level': '4', 'split': 'train'},
       {'index': 4256, 'level': '4', 'split': 'train'},
       {'index': 4256, 'level': '4', 'split': 'train'},
       {'index': 7923, 'level': '4', 'split': 'train'},
       {'index': 7923, 'level': '4', 'split': 'train'},
       {'index': 7923, 'level': '4', 'split': 'train'}], dtype=object), 'index': array([15845, 15845, 15845, 10294, 10294, 4256, 4256, 4256, 7923, 7923,
       7923], dtype=object), 'uid': array(['3d15d528-35bf-4843-a99c-75efd44ed60c',
       '3d15d528-35bf-4843-a99c-75efd44ed60c',
       '3d15d528-35bf-4843-a99c-75efd44ed60c',
       '93f23ffe-97b6-4aa2-8523-1d094d7d5eff',
       '93f23ffe-97b6-4aa2-8523-1d094d7d5eff',
       '593cb8cb-2d8b-406e-ac4d-420403dc0547',
       '593cb8cb-2d8b-406e-ac4d-420403dc0547',
       '593cb8cb-2d8b-406e-ac4d-420403dc0547',
       'c90eb802-85c3-4f6d-9f04-09a370e618be',
       'c90eb802-85c3-4f6d-9f04-09a370e618be',
       'c90eb802-85c3-4f6d-9f04-09a370e618be'], dtype=object)}, meta_info={'global_token_num': [2417, 3337, 3542, 1948, 3350, 4211, 4213, 4213, 4213, 808, 887, 1419, 4212, 4212, 4212, 1409, 1520, 2772], 'temperature': 1.0})

In [ ]:
{'input_ids': tensor([[151643, 151643, 151643,  ..., 151644,  77091,    198],
        [151643, 151643, 151643,  ..., 151644,  77091,    198],
        [151643, 151643, 151643,  ..., 151644,  77091,    198],
        [151643, 151643, 151643,  ..., 151644,  77091,    198],
        [151643, 151643, 151643,  ..., 151644,  77091,    198],
        [151643, 151643, 151643,  ..., 151644,  77091,    198]]), 'attention_mask': tensor([[0, 0, 0,  ..., 1, 1, 1],
        [0, 0, 0,  ..., 1, 1, 1],
        [0, 0, 0,  ..., 1, 1, 1],
        [0, 0, 0,  ..., 1, 1, 1],
        [0, 0, 0,  ..., 1, 1, 1],
        [0, 0, 0,  ..., 1, 1, 1]]), 'position_ids': tensor([[  0,   0,   0,  ..., 113, 114, 115],
        [  0,   0,   0,  ..., 112, 113, 114],
        [  0,   0,   0,  ..., 114, 115, 116],
        [  0,   0,   0,  ..., 108, 109, 110],
        [  0,   0,   0,  ..., 113, 114, 115],
        [  0,   0,   0,  ..., 110, 111, 112]]), 'data_source': array(['countdown', 'countdown', 'countdown', 'countdown', 'countdown',
       'countdown'], dtype=object), 'ability': array(['math', 'math', 'math', 'math', 'math', 'math'], dtype=object), 'reward_model': array([{'ground_truth': {'numbers': array([ 9, 48, 98, 52, 39]), 'target': 46}, 'style': 'rule'},
       {'ground_truth': {'numbers': array([54,  5,  8, 25, 14]), 'target': 90}, 'style': 'rule'},
       {'ground_truth': {'numbers': array([15, 10, 59, 96,  1]), 'target': 800}, 'style': 'rule'},
       {'ground_truth': {'numbers': array([ 8,  1,  1, 29]), 'target': 290}, 'style': 'rule'},
       {'ground_truth': {'numbers': array([71, 85,  9, 79, 40]), 'target': 49}, 'style': 'rule'},
       {'ground_truth': {'numbers': array([32, 21, 50, 45]), 'target': 42}, 'style': 'rule'}],
      dtype=object), 'extra_info': array([{'index': 15845, 'level': '5', 'split': 'train'},
       {'index': 10294, 'level': '5', 'split': 'train'},
       {'index': 19532, 'level': '5', 'split': 'train'},
       {'index': 4256, 'level': '4', 'split': 'train'},
       {'index': 11363, 'level': '5', 'split': 'train'},
       {'index': 7923, 'level': '4', 'split': 'train'}], dtype=object), 'index': array([15845, 10294, 19532, 4256, 11363, 7923], dtype=object)}

In [ ]:
ipdb> gen_batch
DataProto(batch=TensorDict(
    fields={
        attention_mask: Tensor(shape=torch.Size([6, 256]), device=cpu, dtype=torch.int64, is_shared=False),
        input_ids: Tensor(shape=torch.Size([6, 256]), device=cpu, dtype=torch.int64, is_shared=False),
        position_ids: Tensor(shape=torch.Size([6, 256]), device=cpu, dtype=torch.int64, is_shared=False)},
    batch_size=torch.Size([6]),
    device=None,
    is_shared=False), non_tensor_batch={}, meta_info={})
ipdb> batch
DataProto(batch=TensorDict(
    fields={
    },
    batch_size=torch.Size([6]),
    device=None,
    is_shared=False), non_tensor_batch={'data_source': array(['countdown', 'countdown', 'countdown', 'countdown', 'countdown',
       'countdown'], dtype=object), 'ability': array(['math', 'math', 'math', 'math', 'math', 'math'], dtype=object), 'reward_model': array([{'ground_truth': {'numbers': array([ 9, 48, 98, 52, 39]), 'target': 46}, 'style': 'rule'},
       {'ground_truth': {'numbers': array([54,  5,  8, 25, 14]), 'target': 90}, 'style': 'rule'},
       {'ground_truth': {'numbers': array([15, 10, 59, 96,  1]), 'target': 800}, 'style': 'rule'},
       {'ground_truth': {'numbers': array([ 8,  1,  1, 29]), 'target': 290}, 'style': 'rule'},
       {'ground_truth': {'numbers': array([71, 85,  9, 79, 40]), 'target': 49}, 'style': 'rule'},
       {'ground_truth': {'numbers': array([32, 21, 50, 45]), 'target': 42}, 'style': 'rule'}],
      dtype=object), 'extra_info': array([{'index': 15845, 'level': '5', 'split': 'train'},
       {'index': 10294, 'level': '5', 'split': 'train'},
       {'index': 19532, 'level': '5', 'split': 'train'},
       {'index': 4256, 'level': '4', 'split': 'train'},
       {'index': 11363, 'level': '5', 'split': 'train'},
       {'index': 7923, 'level': '4', 'split': 'train'}], dtype=object), 'index': array([15845, 10294, 19532, 4256, 11363, 7923], dtype=object)}, meta_info={})

In [ ]:
corrupt_batch = batch[correct_mask]
corrupt_batch.batch.pop(batch_keys = ["input_ids", "attention_mask", "position_ids"])

In [ ]:
gen_batch_output.batch["responses"][:, -100:]

In [ ]:
batch: DataProto = DataProto.from_single_dict(batch_dict)
                # pop those keys for generation
                gen_batch = batch.pop(batch_keys=['input_ids', 'attention_mask', 'position_ids'])

                score_records = []
                with _timer('step', timing_raw):
                    # generate a batch
                    with _timer('gen', timing_raw):
                        gen_batch_output = self.actor_rollout_wg.generate_sequences(gen_batch)

                    if self.config.algorithm.adv_estimator == 'remax':
                        with _timer('gen_max', timing_raw):
                            gen_baseline_batch = deepcopy(gen_batch)
                            gen_baseline_batch.meta_info['do_sample'] = False
                            gen_baseline_output = self.actor_rollout_wg.generate_sequences(gen_baseline_batch)

                            batch = batch.union(gen_baseline_output)
                            reward_baseline_tensor, score_record = self.reward_fn(batch)
                            reward_baseline_tensor = reward_baseline_tensor.sum(dim=-1)

                            batch.pop(batch_keys=list(gen_baseline_output.batch.keys()))

                            batch.batch['reward_baselines'] = reward_baseline_tensor

                            del gen_baseline_batch, gen_baseline_output

                    batch.non_tensor_batch['uid'] = np.array([str(uuid.uuid4()) for _ in range(len(batch.batch))],
                                                             dtype=object)
                    # repeat to align with repeated responses in rollout
                    batch = batch.repeat(repeat_times=self.config.actor_rollout_ref.rollout.n, interleave=True)
                    batch = batch.union(gen_batch_output)
                    
                    # TODO
                    # HACK: Record total tokens
                    responses_length = batch.batch['responses'].size(-1)
                    self.global_total_tokens += batch.batch['attention_mask'][:, -responses_length:].sum().item()
                    metrics.update({'token_budget/total_token_budget': self.global_total_tokens})
                    # End of HACK

                    # balance the number of valid tokens on each dp rank.
                    # Note that this breaks the order of data inside the batch.
                    # Please take care when you implement group based adv computation such as GRPO and rloo
                    self._balance_batch(batch, metrics=metrics)

                    # compute global_valid tokens
                    batch.meta_info['global_token_num'] = torch.sum(batch.batch['attention_mask'], dim=-1).tolist()

                    # recompute old_log_probs
                    with _timer('old_log_prob', timing_raw):
                        old_log_prob = self.actor_rollout_wg.compute_log_prob(batch)
                        batch = batch.union(old_log_prob)

                    if self.use_reference_policy:
                        # compute reference log_prob
                        with _timer('ref', timing_raw):
                            ref_log_prob = self.ref_policy_wg.compute_ref_log_prob(batch)
                            batch = batch.union(ref_log_prob)

                    # compute values
                    if self.use_critic:
                        with _timer('values', timing_raw):
                            values = self.critic_wg.compute_values(batch)
                            batch = batch.union(values)

                    with _timer('adv', timing_raw):
                        # compute scores. Support both model and function-based.
                        # We first compute the scores using reward model. Then, we call reward_fn to combine
                        # the results from reward model and rule-based results.
                        if self.use_rm:
                            # we first compute reward model score
                            reward_tensor = self.rm_wg.compute_rm_score(batch)
                            batch = batch.union(reward_tensor)

                        # we combine with rule-based rm
                        reward_tensor, score_record = self.reward_fn(batch)
                        score_records.extend(score_record)
                        batch.batch['token_level_scores'] = reward_tensor

                        #HACK: Update reasoning dataset
                        self.update_rollout_dataset(batch, reward_tensor, score_record)
                        
                        # HACK: Record # solve none and solve all and avg solve rate
                        uids = batch.non_tensor_batch['uid']
                        unique_uids = np.unique(uids)
                        valid_mask = torch.ones(len(uids), dtype=torch.bool)
                        solve_none = 0
                        solve_all = 0

                        for uid in unique_uids:
                            uid_mask = uids == uid
                            uid_rewards = reward_tensor[uid_mask].sum(-1)  # Sum rewards for each sequence
                            
                            # Check if all rewards are 0 or all are 1 for this uid
                            if (uid_rewards == 0).all():
                                valid_mask[uid_mask] = False
                                solve_none += 1
                            elif (uid_rewards == 1).all():
                                valid_mask[uid_mask] = False
                                solve_all += 1
                        
                        # Log to metrics
                        metrics['batch/solve_none'] = solve_none
                        metrics['batch/solve_all'] = solve_all
                        metrics['batch/avg_solve_rate'] = batch[valid_mask].batch['token_level_scores'].sum(-1).mean().item()

In [ ]:
                    if not self.config.actor_rollout_ref.actor.get('use_kl_loss', False):
                        batch, kl_metrics = apply_kl_penalty(batch,
                                                             kl_ctrl=self.kl_ctrl,
                                                             kl_penalty=self.config.algorithm.kl_penalty)
                        metrics.update(kl_metrics)
                    else:
                        batch.batch['token_level_rewards'] = batch.batch['token_level_scores']

                    # compute advantages, executed on the driver process
                    batch = compute_advantage(batch,
                                              adv_estimator=self.config.algorithm.adv_estimator,
                                              gamma=self.config.algorithm.gamma,
                                              lam=self.config.algorithm.lam,
                                              num_repeat=self.config.actor_rollout_ref.rollout.n)

                # update critic
                if self.use_critic:
                    with _timer('update_critic', timing_raw):
                        critic_output = self.critic_wg.update_critic(batch)
                    critic_output_metrics = reduce_metrics(critic_output.meta_info['metrics'])
                    metrics.update(critic_output_metrics)

                # implement critic warmup
                if self.config.trainer.critic_warmup <= self.global_steps:
                    # update actor
                    with _timer('update_actor', timing_raw):
                        actor_output = self.actor_rollout_wg.update_actor(batch)
                    actor_output_metrics = reduce_metrics(actor_output.meta_info['metrics'])
                    metrics.update(actor_output_metrics)

                with _timer('log_scores', timing_raw):
                    score_metrics = self._log_scores_to_wandb(score_records, epoch)
                    # Update metrics with returned values instead of direct logging
                    # logger.log(data=score_metrics, step=self.global_steps)
                    metrics.update(score_metrics)

In [ ]:
ipdb> output[1]
tensor([[-1.2297e-03, -1.1921e-07, -2.0623e-05,  ...,  1.5164e+05,
          1.5164e+05,  1.5164e+05],
        [-1.2297e-03, -1.1921e-07, -2.0623e-05,  ...,  1.5164e+05,
          1.5164e+05,  1.5164e+05],
        [-1.2297e-03, -1.1921e-07, -2.0623e-05,  ...,  1.5164e+05,
          1.5164e+05,  1.5164e+05],
        ...,
        [-1.3803e-03, -1.1921e-07, -2.0623e-05,  ...,  1.5164e+05,
          1.5164e+05,  1.5164e+05],
        [-1.3803e-03, -1.1921e-07, -2.0623e-05,  ...,  1.5164e+05,
          1.5164e+05,  1.5164e+05],
        [-1.3803e-03, -1.1921e-07, -2.0623e-05,  ...,  1.5164e+05,
          1.5164e+05,  1.5164e+05]])
ipdb> output[0]
tensor([[ 13708,    766,    397,  ..., 151643, 151643, 151643],
        [ 13708,    766,    397,  ..., 151643, 151643, 151643],
        [ 13708,    766,    397,  ..., 151643, 151643, 151643],
        ...,
        [ 13708,    766,    397,  ..., 151643, 151643, 151643],
        [ 13708,    766,    397,  ..., 151643, 151643, 151643],
        [ 13708,    766,    397,  ..., 151643, 151643, 151643]])
ipdb> output[0].shape
torch.Size([18, 4096])
ipdb> output[1]
tensor([[-1.2297e-03, -1.1921e-07, -2.0623e-05,  ...,  1.5164e+05,
          1.5164e+05,  1.5164e+05],
        [-1.2297e-03, -1.1921e-07, -2.0623e-05,  ...,  1.5164e+05,
          1.5164e+05,  1.5164e+05],
        [-1.2297e-03, -1.1921e-07, -2.0623e-05,  ...,  1.5164e+05,
          1.5164e+05,  1.5164e+05],
        ...,
        [-1.3803e-03, -1.1921e-07, -2.0623e-05,  ...,  1.5164e+05,
          1.5164e+05,  1.5164e+05],
        [-1.3803e-03, -1.1921e-07, -2.0623e-05,  ...,  1.5164e+05,
          1.5164e+05,  1.5164e+05],
        [-1.3803e-03, -1.1921e-07, -2.0623e-05,  ...,  1.5164e+05,
          1.5164e+05,  1.5164e+05]])
ipdb> output[1].shape
torch.Size([18, 4096])
ipdb>

In [ ]:
evals
    0. same set of stress tests for both math and countdown
    1. if observations on countdown and math are consistent
    2. if the corruption happens in the first chunk
    3. check the eval results for sft 3 epoch

In [ ]:
training todo:
    
    mix original question and corrupted prefix
    1. collect offline rl prefix ==> rl (save checkpoints for later eval)
    2. rl on same flops ==> same number of problems (assuming problems i.i.d)
    3. 1st rl collect for rejection sampling
    
    
generalization:
    1. different types of corruption (distractor injection, just wrong answer at the end)
    2. different degrees of digit corruption
    3. different task complexity

In [ ]:
generate more level 5, 6, 7 questions 50K each
use r1 to generate corrupted prefix + collect recovery + not recover (50 50)

we can launch 2 first